# Nivell 1

    Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.
    Exploració bàsica amb una API de laboratori.
    
    1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
        Llista de publicacions (/posts)
        Llista d’usuaris (/users)
        Llista de tasques (/todos)

In [3]:
# python -m pip install requests
import requests
from pprint import pprint
import pandas as pd

In [4]:
url_inicial = 'https://jsonplaceholder.typicode.com'
def obtener_listas(endpoint):
    url = f'{url_inicial}/{endpoint}'
    r = requests.get(url)
    print(f'Endpoint: /{endpoint}')
    print('Código de estado: ', r.status_code)
    datos = r.json()
    print(f'Datos de {endpoint}: {datos}')
    return datos

posts = obtener_listas('posts')
users = obtener_listas('users')
todos = obtener_listas('todos')

Endpoint: /posts
Código de estado:  200

    2. Mostra per pantalla:
        La quantitat total de cada recurs.
        El codi d'estat de cada petició.

In [5]:
url_inicial = 'https://jsonplaceholder.typicode.com'
def obtener_listas(endpoint):
    url = f'{url_inicial}/{endpoint}'
    r = requests.get(url)
    print(f'Endpoint: /{endpoint}')
    print('Código de estado: ', r.status_code)
    total = len(r.json())
    print(f'Total {endpoint}: {total}')
    return total

total_posts = obtener_listas('posts')
total_users = obtener_listas('users')
total_todos = obtener_listas('todos')

Endpoint: /posts
Código de estado:  200
Total posts: 100
Endpoint: /users
Código de estado:  200
Total users: 10
Endpoint: /todos
Código de estado:  200
Total todos: 200

    3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [21]:
url_inexistente = f'{url_inicial}/posts/oij99hvgv99X'
respuesta_404 = requests.get(url_inexistente)

print(f'Petición a publicacion inexistente: {url_inexistente}')
print('Codigo de estado:', respuesta_404.status_code)
print('Respuesta:', respuesta_404.text)

Petición a publicacion inexistente: https://jsonplaceholder.typicode.com/posts/oij99hvgv99X
Codigo de estado: 404
Respuesta: {}

    4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
        Mostra la resposta JSON.
        Mostra el codi d'estat.

In [7]:
nueva_public = {'title': 'Titulo de prueba ficticia', 'body': 'Aqui se pone el contenido de la publicacion.', 'userID': 1}

url_posts = f'{url_inicial}/posts'
respuesta_post = requests.post(url_posts, json = nueva_public)

print('Crear nuevo post.', 'Codigo de estado:', respuesta_post.status_code)
print('Respuesta JSON:', respuesta_post.json())

Crear nuevo post. Codigo de estado: 201
Respuesta JSON: {'title': 'Titulo de prueba ficticia', 'body': 'Aqui se pone el contenido de la publicacion.', 'userID': 1, 'id': 101}

    5. Fes una petició PATCH per modificar parcialment una publicació existent.
        Mostra la resposta JSON.
        Mostra el codi d'estat.

In [8]:
actualizar_public = {'title': 'Titulo modificado'}

url_actualiza = f'{url_inicial}/posts/1'
respuesta_patch = requests.patch(url_actualiza, json = actualizar_public)

print('Actualizar post con PATCH:', 'Codigo de estado:', respuesta_patch.status_code)
print('Respuesta JSON:', respuesta_patch.json())

Actualizar post con PATCH: Codigo de estado: 200
Respuesta JSON: {'userId': 1, 'id': 1, 'title': 'Titulo modificado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

    6. Fes una petició DELETE sobre una publicació.
        Mostra la resposta JSON.
        Mostra el codi d'estat.

In [9]:
url_borrar = f'{url_inicial}/posts/1'
respuesta_delete = requests.delete(url_borrar)

print('Borrar post:', 'Codigo de estado:', respuesta_delete.status_code)
print('Respuesta JSON:', respuesta_delete.text)

Borrar post: Codigo de estado: 200
Respuesta JSON: {}

# Nivell 2

    Interacció amb una API pública real

    1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

        API elegida: Open library
        categoria: Books
        web: https://openlibrary.org/

    2. Llegeix la documentació de l'API:
        Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
        Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
        Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

        * Endpoints elegidos:
        '/search.json'   # parametros:'q', 'title', 'author', 'page', 'limit'
        '/isbn/(numero 13 digitos).json'

        ejemplos:
        'https://openlibrary.org/search.json?q=harry+potter'
        
        'https://openlibrary.org/isbn/9781631593710.json'

In [10]:
# Verifico si respuesta es en json, aunque el endpoint ya lo indica.

url = "https://openlibrary.org/search.json"
params = {"q": "harry potter"}

#url = "https://openlibrary.org/isbn/9781631593710.json"

r = requests.get(url, params=params)

print("Content-Type:", r.headers.get("Content-Type"))
print("¿JSON válido?:", isinstance(r.json(), dict))

Content-Type: application/json
¿JSON válido?: True

    3. Fes una petició GET senzilla:
        Mostra el codi d'estat de la resposta.
        Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [11]:
url_search= "https://openlibrary.org/search.json"
params = {"q": "harry potter", "limit": 10}

r = requests.get(url_search, params=params)

print("url search:", r.url)
print("codigo de estado:", r.status_code)

datos_resp= r.json()

docs = datos_resp.get("docs", [])

if docs:
    primero = docs[0]
    pprint(list(primero.keys()))
    #pprint(primero)
else:
    print("No hay resultados")

url search: https://openlibrary.org/search.json?q=harry+potter&limit=10
codigo de estado: 200
['author_key',
 'author_name',
 'cover_edition_key',
 'cover_i',
 'ebook_access',
 'edition_count',
 'first_publish_year',
 'has_fulltext',
 'ia',
 'ia_collection',
 'key',
 'language',
 'lending_edition_s',
 'lending_identifier_s',
 'public_scan_b',
 'title']

In [12]:
if docs:
    primero = docs[0]
    print(f"Titulo: {primero.get("title")} | "
    f"Autores: {primero.get("author_name")} | "
    f"Año 1ra publicacion: {primero.get("first_publish_year")}")

Titulo: Harry Potter and the Philosopher's Stone | Autores: ['J. K. Rowling'] | Año 1ra publicacion: 1997

    4. Converteix les dades a un DataFrame de pandas:
        Mostra les primeres files del DataFrame.

In [13]:
registros = []

for libro in docs:
    registros.append({"title": libro.get("title"), "author": ", ".join(libro.get("author_name", []))
    if libro.get("author_name")
    else None,
    "first_publish_year": libro.get("first_publish_year"), "edition_count": libro.get("edition_count"), })

df_libros =pd.DataFrame(registros)
df_libros.head()

,title,author,first_publish_year,edition_count
0,Harry Potter and the Philosopher's Stone,J. K. Rowling,1997,393
1,Harry Potter and the Deathly Hallows,J. K. Rowling,2007,144
2,Harry Potter and the Prisoner of Azkaban,J. K. Rowling,1999,278
3,Harry Potter and the Goblet of Fire,J. K. Rowling,2000,242
4,Harry Potter and the Order of the Phoenix,J. K. Rowling,2003,246

# Nivell 3

    API d'Open Data Barcelona
    1. Utilitza l’API d’Open Data BCN per:
        Cercar un dataset del teu interès mitjançant package_search i package_show.

In [14]:
url_base = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

# Consulta usando package_search - se buscan varios datasets con la palabra "arbra" y un máximo de 10 datasets.
paramet_search = {"q": "arbrat", "rows": 10}

r_search_bcn = requests.get(f"{url_base}/package_search", params = paramet_search)

print("codigo de estado:" , r_search_bcn.status_code)

data_search_bcn = r_search_bcn.json()

codigo de estado: 200

In [15]:
# Reviso los resultados para elgir un dataset
datasets = data_search_bcn["result"]["results"]

print("Num datasets:", len(datasets))

for ds in datasets:
    print(f"ID: {ds['id']}  |"
        f"Nombre: {ds['name']}  |"
        f"Titulo: {ds['title']}")

Num datasets: 7
ID: 42caea89-ac58-40d6-b60a-2b604d2dfadc  |Nombre: atles-biodiversitat-arbrat-rel-geometria-especie  |Titulo: Geometry-species relationship of the trees of the Biodiversity Atlas of the city of Barcelona
ID: 2144fbd7-13dd-4708-9db6-02300f23cb7a  |Nombre: atles-biodiversitat-arbrat-geometries  |Titulo: Inventory of tree geometries of the Biodiversity Atlas of the city of Barcelona
ID: ecc4466b-6bfc-443d-b223-375ff426067b  |Nombre: atles-biodiversitat-arbrat-especies  |Titulo: Inventory of tree species of the Atlas of Biodiversity of the city of Barcelona
ID: 99ce00b1-36ab-4e06-b1bc-c60c5f7a811d  |Nombre: arbrat-parcs  |Titulo: Trees in the parks of the city of Barcelona
ID: 9b525e1d-13b8-48f1-abf6-f5cd03baa1dd  |Nombre: arbrat-zona  |Titulo: Zone trees of the city of Barcelona
ID: 7052709e-1087-4ef3-862a-1a6c3e9a7200  |Nombre: arbres-interes-local  |Titulo: Local interest trees from Barcelona
ID: 27b3f8a7-e536-4eea-b025-ce094817b2bd  |Nombre: arbrat-viari  |Titulo: Street trees of the city of Barcelona

In [16]:
# Dataset elegido
dataset_id = "9b525e1d-13b8-48f1-abf6-f5cd03baa1dd"

# Utilizo package_show - para ver los detalles de mi dataset
r_show_bcn = requests.get(f"{url_base}/package_show", params = {"id": dataset_id})

print("codigo de estado (package_show):" , r_show_bcn.status_code)

data_show_bcn = r_show_bcn.json()

dataset = data_show_bcn["result"]

codigo de estado (package_show): 200

    2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [17]:
# transformo a Dataframe con pandas, para visualizar mejor mi resultado y filtrado.

resources = dataset["resources"]

resumen_resources = [{"id": r["id"], "name": r.get("name"), "format": r.get("format"), "url": r.get("url"),}
    for r in resources]

df_resources =pd.DataFrame(resumen_resources)

df_resources_filtrado = df_resources[df_resources["format"].str.upper().isin(["CSV","JSON"])]
df_resources_filtrado

,id,name,format,url
0,7984c323-e2f5-47a0-af66-e03f03767494,OD_Arbrat_Zona_BCN.json,JSON,https://opendata-ajuntament.barcelona.cat/data...
1,29cd5c1f-11b1-404b-b3a5-ae29940b8c55,OD_Arbrat_Zona_BCN.csv,CSV,https://opendata-ajuntament.barcelona.cat/data...

    3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:
        Recuperar almenys 100 registres.

In [18]:
# Recurso selecionado
resource_id = "29cd5c1f-11b1-404b-b3a5-ae29940b8c55"

# Consulta con datastore_search
params_data = {"resource_id": resource_id, "limit": 100}

r_data = requests.get(f"{url_base}/datastore_search", params = params_data)

print("codigo de estado (datastore_search):", r_data.status_code)

data = r_data.json()

records = data["result"]["records"]
print("Registros recuperados:", len(records))

codigo de estado (datastore_search): 200
Registros recuperados: 100

    4. Converteix els resultats a un DataFrame.

In [19]:
df = pd.DataFrame(records)
df

,latitud,cat_nom_catala,codi,espai_verd,adreca,catalogacio,nom_districte,tipus_element,cat_nom_castella,nom_barri,...,data_plantacio,codi_barri,longitud,codi_districte,tipus_reg,categoria_arbrat,cat_especie_id,tipus_aigua,y_etrs89,_id
0,41.4365081,Palmera datilera; palmera de dàtils,0000377AR,"Central de Nou Barris, Parc","Pl Major de Nou Barris, 0",,NOU BARRIS,PALMERA ZONA,Palmera datilera,LA GUINEUETA,...,None,48,2.1705107,8,GOTEIG,TERCERA,48,,4587547.432,1
1,41.4377690,Plàtan,0000386AR,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",,HORTA - GUINARDÓ,ARBRE ZONA,Plátano,HORTA,...,None,43,2.1625299,7,SENSE INFORMAR,SEGONA,126,,4587693.836,2
2,41.4377883,Plàtan,0000387AR,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",,HORTA - GUINARDÓ,ARBRE ZONA,Plátano,HORTA,...,None,43,2.1625008,7,SENSE INFORMAR,SEGONA,126,,4587696.005,3
3,41.4378096,Plàtan,0000388AR,"Central de Nou Barris, Parc","C\ Doctor Letamendi, 90",,HORTA - GUINARDÓ,ARBRE ZONA,Plátano,HORTA,...,None,43,2.1624711,7,SENSE INFORMAR,TERCERA,126,,4587698.393,4
4,41.4352512,Pi blanc,0000389AR,"Central de Nou Barris, Parc","C\ Borgonya, 2",,NOU BARRIS,ARBRE ZONA,Pino carrasco,LA GUINEUETA,...,None,48,2.1690974,8,DIFUSIÓ,EXEMPLAR,99,,4587409.021,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,41.4375861,Magnòlia,0001478AR,"Ca n'Ensenya, pl.","Pl Ca n'Ensenya, 0",,NOU BARRIS,ARBRE ZONA,Magnolio; magnolio común,LA GUINEUETA,...,2024-09-04T00:00:00,48,2.1705890,8,GOTEIG,PRIMERA,694,POTABLE,4587667.048,95
96,41.4375850,Magnòlia,0001484AR,"Ca n'Ensenya, pl.","Pl Ca n'Ensenya, 0",,NOU BARRIS,ARBRE ZONA,Magnolio; magnolio común,LA GUINEUETA,...,None,48,2.1706499,8,MÀNEGA,SEGONA,694,POTABLE,4587666.875,96
97,41.4383717,Nesprer del Japó,0001489AR,"Can Ensenya, c. (Fabra i Puig, Pg. 437( interi...","Pg Fabra i Puig, 433",,NOU BARRIS,ARBRE ZONA,Níspero del Japón,LA GUINEUETA,...,None,48,2.1649842,8,MÀNEGA,PRIMERA,1359,,4587758.771,97
98,41.4384501,Pollancre gavatx,0001521AR,"Constància, Jardins","Pg Valldaura, 156",,NOU BARRIS,ARBRE ZONA,Chopo lombardo,LA GUINEUETA,...,None,48,2.1668155,8,GOTEIG,TERCERA,152,,4587766.000,98
99,41.4342080,Alzina,0134265AR,"Sóller, Pl.","Pl Sóller, 0",,NOU BARRIS,ARBRE ZONA,Encina,PORTA,...,None,45,2.1756459,8,ROTATOR,SEGONA,238,,4587287.975,4420

    5. Desa el DataFrame en un fitxer .csv.

In [20]:
df.to_csv("datos_arbrat_zona.csv", index=False, encoding="utf-8")